# Basic colors
foreground              #eedfe3
background              #191114
selection_foreground    #fed9e7
selection_background    #59404a

# Cursor colors
cursor                  #feb0d3
cursor_text_color       #521d3a

# URL underline color when hovering with mouse
url_color               #f2bb99

# Kitty window border colors
active_border_color     #feb0d3
inactive_border_color   #504348
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #ffd8e7
active_tab_background   #6d3351
inactive_tab_foreground #d4c2c8
inactive_tab_background #251d20
tab_bar_background      #191114

# Colors for marks
mark1_foreground #521d3a
mark1_background #feb0d3
mark2_foreground #412a34
mark2_background #e0bdcb
mark3_foreground #492810
mark3_background #f2bb99

# The 16 terminal colors
# black
color0 #504348
color8 #9d8d92

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #feb0d3
color10 #ffd8e7

# yellow
color3  #f2bb99
color11 #ffdbc7

# blue
color4  #e0bdcb
color12 #fed9e7

# magenta
color5  #6d3351
color13 #894a69

# cyan
color6  #59404a
color14 #643e24

# white
color7  #d4c2c8
color15 #eedfe3
