# Basic colors
foreground              #e8e0e8
background              #151217
selection_foreground    #eeddf6
selection_background    #4e4256

# Cursor colors
cursor                  #dcb9f8
cursor_text_color       #3f2358

# URL underline color when hovering with mouse
url_color               #f3b7bc

# Kitty window border colors
active_border_color     #dcb9f8
inactive_border_color   #4b454d
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #f1daff
active_tab_background   #573a70
inactive_tab_foreground #cdc4ce
inactive_tab_background #221e24
tab_bar_background      #151217

# Colors for marks
mark1_foreground #3f2358
mark1_background #dcb9f8
mark2_foreground #372c3f
mark2_background #d1c1d9
mark3_foreground #4c252a
mark3_background #f3b7bc

# The 16 terminal colors
# black
color0 #4b454d
color8 #968e98

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #dcb9f8
color10 #f1daff

# yellow
color3  #f3b7bc
color11 #ffdadc

# blue
color4  #d1c1d9
color12 #eeddf6

# magenta
color5  #573a70
color13 #705289

# cyan
color6  #4e4256
color14 #663a3f

# white
color7  #cdc4ce
color15 #e8e0e8
