# Matugen template: kitty terminal color scheme from wallpaper
foreground            #e4e1ec
background            #13131a
selection_foreground  #14149a
selection_background  #bfc1ff
url_color             #ffb68d
cursor                #bfc1ff
cursor_text_color     #14149a

color0   #13131a
color1   #ffb4ab
color2   #bfc1ff
color3   #ffb68d
color4   #bfc1ff
color5   #ffb68d
color6   #934200
color7   #e4e1ec

color8   #908f9f
color9   #ffb4ab
color10  #bfc1ff
color11  #ffb68d
color12  #bfc1ff
color13  #ffb68d
color14  #934200
color15  #e4e1ec

tab_bar_background              #13131a
tab_bar_margin_color            #13131a
active_tab_foreground           #14149a
active_tab_background           #bfc1ff
inactive_tab_foreground         #c6c5d6
inactive_tab_background         #13131a
