$wallpaper = /home/revo/.config/wallpapers/girl-laying-down.jpg
$background = 131413
$foreground = e4e2e1

$primary = b7cbc3
$secondary = c1c8c4
$tertiary = c8c4d7
$surface = 131413
$surface_bright = 393938
$outline = 8c928f
$error = 000000

$shadow = 000000
