# src/config/hyprlock.conf

$font = JetBrainsMono Nerd Font
$font_bold = JetBrainsMono Nerd Font ExtraBold

# Source the dynamically generated Matugen colors
source = ~/.local/src/Brain_Shell/src/config/colors.conf

# BACKGROUND
background {
    monitor =
    path = ~/.curr_wall_static.jpg
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
}

# Day
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A")"
    color = rgb($primary)
    font_size = 90
    font_family = $font_bold
    position = 0, 350
    halign = center
    valign = center
}

# Date-Month
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %B")"
    color = rgb($primary)
    font_size = 40
    font_family = $font_bold
    position = 0, 250
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"- %I:%M -")</span>"
    color = rgb($primary)
    font_size = 20
    font_family = $font_bold
    position = 0, 190
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 300, 60
    color = rgb($surface)
    rounding = -1
    border_size = 0
    border_color = rgb(255, 255, 255, 0)
    rotate = 0
    xray = false 

    position = 0, -130
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = rgb($surface_bright)
    font_size = 18
    font_family = $font_bold
    position = 0, -130
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2 
    dots_spacing = 0.2 
    dots_center = true
    
    # Fully integrated Matugen variables
    outer_color = rgb($outline)
    inner_color = rgb($surface_bright)
    font_color = rgb($primary)
    
    fade_on_empty = false
    font_family = $font_bold
    placeholder_text = <i>🔒 Enter Pass</i>
    hide_input = false
    position = 0, -210
    halign = center
    valign = center
}

# Suspend
label {
    monitor =
    text = 󰤄 
    color = rgb($secondary)
    font_size = 45
    font_family = $font
    onclick = systemctl suspend
    # Anchored to center, shifted left
    position = -200, 100
    halign = center
    valign = bottom
}

# Reboot
label {
    monitor =
    text = 󰜉 
    color = rgb($secondary)
    font_size = 45
    font_family = $font
    onclick = reboot now
    # Anchored perfectly in the center
    position = 0, 100
    halign = center
    valign = bottom
}

# Power off
label {
    monitor =
    text = 󰐥 
    color = rgb($secondary)
    font_size = 45
    font_family = $font
    onclick = shutdown now
    # Anchored to center, shifted right
    position = 200, 100
    halign = center 
    valign = bottom
}
