[config]
# Mandatory config section for matugen

[templates.brain_shell]
input_path = './brain-shell-colors.json.example'
output_path = '~/.cache/brain-shell/colors.json'

[templates.hyprland_colors]
input_path = "colors.conf.template"
output_path = "colors.conf"