require("colors")
require("configs.monitors")
require("configs.env")
require("configs.input")
require("configs.general")
require("configs.animations")
require("configs.debug")
require("configs.hyprcolors")
require("configs.windowrule")
require("configs.keybinds")
require("configs.autostart")
require("configs.hyprglass")
require("configs.hypr3d")

-- Brain_ShellKeybinds
dofile("/home/revo/.config/Brain_Shell/Brain_ShellKeybinds.lua")
