plugin = /var/cache/hyprpm/revo/HyprGlass/hyprglass.so

source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/general.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/windowrule.conf
source = ~/.config/hypr/configs/macos.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/debug.conf
source = ~/.config/hypr/configs/hyprcolors.conf

# Generated binds are stored in ~/.config/tide-island/hyprland-shortcuts.conf.
# They call Quickshell IPC and can also be reused from your own scripts.
source = /home/revo/.config/tide-island/hyprland-shortcuts.conf

exec-once = dynamic-glacier
