-- Generated by Ryoku Settings (Super + ,). Lives in the user_edits overlay,
-- overwritten on every change, so change it in the GUI, not by hand. Loaded
-- after Ryoku's defaults and before your user.lua, which still wins.

hl.config({
  input = { kb_layout = "us,ara", kb_variant = "[[EMPTY]]", kb_options = "grp:alt_shift_toggle" },
})

