# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ KEYBINDINGS — Revo Custom
#  أضف كيبايندزك هنا. لا تعدّل على ملفات أخرى
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

$mainMod = SUPER

# أضف keybinds هنا ↓
