# Matugen template for btop

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal:
# "#RRGGBB", "#BW" or "0-255 0-255 0-255".

# Main background must remain empty for terminal transparency.
theme[main_bg]=""
theme[main_fg]="{{colors.on_surface.default.hex}}"
theme[title]="{{colors.primary.default.hex}}"
theme[hi_fg]="{{colors.secondary.default.hex}}"
theme[selected_bg]="{{colors.primary.default.hex}}"
theme[selected_fg]="{{colors.on_primary.default.hex}}"
theme[inactive_fg]="{{colors.on_surface_variant.default.hex}}"
theme[proc_misc]="{{colors.tertiary.default.hex}}"

theme[cpu_box]="{{colors.outline.default.hex}}"
theme[mem_box]="{{colors.outline.default.hex}}"
theme[net_box]="{{colors.outline.default.hex}}"
theme[proc_box]="{{colors.outline.default.hex}}"
theme[div_line]="{{colors.outline_variant.default.hex}}"

theme[temp_start]="{{colors.secondary.default.hex}}"
theme[temp_mid]="{{colors.primary.default.hex}}"
theme[temp_end]="{{colors.error.default.hex}}"

theme[cpu_start]="{{colors.secondary.default.hex}}"
theme[cpu_mid]="{{colors.primary.default.hex}}"
theme[cpu_end]="{{colors.error.default.hex}}"

theme[free_start]="{{colors.secondary.default.hex}}"
theme[free_mid]=""
theme[free_end]="{{colors.secondary_container.default.hex}}"

theme[cached_start]="{{colors.tertiary.default.hex}}"
theme[cached_mid]=""
theme[cached_end]="{{colors.tertiary_container.default.hex}}"

theme[available_start]="{{colors.primary.default.hex}}"
theme[available_mid]=""
theme[available_end]="{{colors.primary_container.default.hex}}"

theme[used_start]="{{colors.error.default.hex}}"
theme[used_mid]=""
theme[used_end]="{{colors.error_container.default.hex}}"

theme[download_start]="{{colors.secondary.default.hex}}"
theme[download_mid]="{{colors.primary.default.hex}}"
theme[download_end]="{{colors.tertiary.default.hex}}"

theme[upload_start]="{{colors.secondary.default.hex}}"
theme[upload_mid]="{{colors.primary.default.hex}}"
theme[upload_end]="{{colors.tertiary.default.hex}}"
