import QtQuick
pragma Singleton

QtObject {
    readonly property string networkEthernet: "󰈀"
    readonly property string networkWifiConnected: "󰖩"
    readonly property string networkWifiDisconnected: "󰖪"
    readonly property string volumeMuted: "󰖁"
    readonly property string volumeZero: "󰝟"
    readonly property string volumeLow: "󰕿"
    readonly property string volumeMedium: "󰖀"
    readonly property string volumeHigh: "󰕾"
    readonly property string batteryUnknown: "󰂎"
    readonly property string batteryCharging: "󰂄"
    readonly property string battery100: "󰁹"
    readonly property string battery90: "󰂂"
    readonly property string battery80: "󰂁"
    readonly property string battery70: "󰂀"
    readonly property string battery60: "󰁿"
    readonly property string battery50: "󰁾"
    readonly property string battery40: "󰁽"
    readonly property string battery30: "󰁼"
    readonly property string battery20: "󰁻"
    readonly property string battery10: "󰁺"
    readonly property string battery0: "󰂎"
    readonly property string arrowLeft: ""
    readonly property string power: "⏻"
    readonly property string star: ""
    readonly property string back: "󰁮"
    readonly property string settings: "󰒓"
    readonly property string check: ""
    readonly property string bell: "󰂚"
    readonly property string lock: "󰌾"
    readonly property string suspend: "󰒲"
    readonly property string reload: "󰑓"
    readonly property string shutdown: "󰐥"
    readonly property string logout: "󰍃"
    readonly property string arch: "󰣇"
    readonly property string music: "󰝚"
    readonly property string weather: "󰖐"
    readonly property string system: "󰍛"
    readonly property string bluetooth: "󰂯"
    readonly property string airplane: "󰀝"
    readonly property string dnd: "󰂛"
    readonly property string brightness: "󰃠"
    readonly property string temperature: "󰔏"
    readonly property string temperatureLow: "󰔎"
    readonly property string temperatureMedium: "󰔐"
    readonly property string fire: "󰈸"
    readonly property string snowflake: "󰖘"

}