hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon & sleep 1; " .. os.getenv("HOME") .. "/.config/hypr/scripts/wallpapers/set-random.sh")
    hl.exec_cmd("hyprshade on vibrance")
    hl.exec_cmd("skwd")
    hl.exec_cmd("~/.config/skwd/scripts/bash/restore-wallpaper")
    hl.exec_cmd("quickshell -p ~/.config/hypr/scripts/quickshell/Main.qml")
    hl.exec_cmd("quickshell -p ~/.config/hypr/scripts/quickshell/TopBar.qml")
    hl.exec_cmd("python3 ~/.config/hypr/scripts/quickshell/focustime/focus_daemon.py &")
    hl.exec_cmd("~/.config/hypr/scripts/init.sh")
    hl.exec_cmd("~/.config/hypr/scripts/qs_manager.sh toggle guide &")
    hl.exec_cmd("playerctld")
    hl.exec_cmd("swayosd-server --top-margin 0.9")
    hl.exec_cmd("~/.config/hypr/scripts/volume_listener.sh")
    hl.exec_cmd("~/.config/hypr/scripts/settings_watcher.sh &")
    hl.exec_cmd("~/.config/hypr/scripts/update_notifier.sh &")
    hl.exec_cmd("systemctl --user enable --now easyeffects")
    hl.exec_cmd("quickshell -p ~/.config/hypr/scripts/quickshell/Powermenu.qml")
    hl.exec_cmd("powerprofilesctl set performance")
    hl.exec_cmd("hyprctl setcursor QingyiBLZ 24")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'QingyiBLZ'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 24")
    hl.exec_cmd("/home/revo/.config/hypr/sounds/keysound.py")
    h.exec_once("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
h.exec_once("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
h.exec_once("systemctl --user restart xdg-desktop-portal-hyprland xdg-desktop-portal-gtk xdg-desktop-portal")
end)
