hl.env("XCURSOR_THEME", "QingyiBLZ")
hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_THEME", "QingyiBLZ")
hl.env("PATH", "/home/revo/.local/bin:" .. os.getenv("PATH"))
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("OMARCHY_LOOKING_GLASS", 1)
hl.env("IVSHMEM_KEY", "omarchy-win-vm")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("SCREENSHOT_PROVIDER", "ext-image-copy-capture-v1")
hl.env("NVD_BACKEND", "direct")
hl.env("WEBRTC_FORCE_HW_CODEC", "1")
hl.env("GTK_THEME", "MacTahoe-Dark-solid")
