# Variables
$inFocusOpacity = 0.9
$notInFocusOpacity = 0.7

windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Default opacity for all windows
windowrule = opacity $inFocusOpacity $notInFocusOpacity, match:class .*

# Kitty fully opaque
windowrule = opacity 1 1, match:class ^kitty$

# Browsers
windowrule = opacity $inFocusOpacity $notInFocusOpacity, match:class ^(firefox|brave|chromium|librewolf|qutebrowser|zen-browser)$

# Spotify / Discord / Telegram / VS Code / Thunar or Nemo by title
windowrule = opacity $inFocusOpacity $notInFocusOpacity, match:title .*Spotify.*
windowrule = opacity $inFocusOpacity $notInFocusOpacity, match:title .*Discord.*
windowrule = opacity $inFocusOpacity $notInFocusOpacity, match:title .*Telegram.*
windowrule = opacity $inFocusOpacity $notInFocusOpacity, match:title .*Code.*
windowrule = opacity $inFocusOpacity $notInFocusOpacity, match:title .*(Thunar|nemo).*

windowrule = match:class ^(gamescope)$, immediate 1
windowrule = match:class ^(gamescope)$, fullscreen 1

# PearOS Settings: floating centered window
windowrule = match:class ^(pearos-settings-app)$, float
windowrule = match:class ^(pearos-settings-app)$, center
windowrule = match:class ^(pearos-settings-app)$, size 700 600
windowrule = match:class ^(pearos-settings-app)$, no_shadow
windowrule = tag:hyprglass_preset_liquid_true, class:^(pearos-settings-app)$
